name: PowerfulPerms
main: com.github.cheesesoftware.PowerfulPerms.PowerfulPerms
version: ${version}
author: gustav9797
softdepend: [Vault, PlaceholderAPI]

commands:
 powerfulperms:
  description: The global command of PowerfulPerms for modifying permissions.
  aliases: [pp, pop, pow]